notifications:
  createIssues:
    repository: "quarkusio/quarkus-github-lottery-reports"
buckets:
  triage:
    label: "triage/needs-triage"
    delay: PT0S
    timeout: P3D
  maintenance:
    feedback:
      labels: ["triage/needs-reproducer", "triage/needs-feedback"]
      needed:
        delay: P21D
        timeout: P3D
      provided:
        delay: P7D
        timeout: P3D
    stale:
      delay: P60D
      timeout: P14D
  stewardship:
    delay: P21D
    timeout: P3D
participants:
  - username: "gsmet"
    timezone: "Europe/Paris"
    stewardship:
      days: ["MONDAY"]
      maxIssues: 3
  - username: "maxandersen"
    timezone: "Europe/Paris"
    triage:
      days: ["WEDNESDAY", "FRIDAY"]
      maxIssues: 3
    stewardship:
      days: ["WEDNESDAY", "FRIDAY"]
      maxIssues: 3
  - username: "marko-bekhta"
    timezone: "Europe/Warsaw"
    maintenance:
      labels: ["area/search"]
      days: ["WEDNESDAY", "FRIDAY"]
      feedback:
        needed:
          maxIssues: 2
        provided:
          maxIssues: 2
      stale:
        maxIssues: 2