# Configuration for development

# We don't want to use the production instance of search.quarkus.io for development.
search:

# By default we use the staging cluster in direct mode, you can change it to use your local instance if running
# Use "direct" to directly use the script from the search instance
# Use "cached" to use a local copy of the search script copied from the search instance
  script-mode: "direct"
#  host: "http://localhost:8080"
  host: "https://search-quarkus-io-dev-search-quarkus-io.apps.ospo-osci.z3b1.p1.openshiftapps.com"

