headline: "Training courses offered by members of the community."
disclaimer: "Trainings listed here are offered by outside services and are not affiliated with the Quarkus project. The Quarkus project is not responsible for their content."

courses:

- url: "https://agoncal.teachable.com/courses/category/quarkus"
  note: "Quarkus courses offered by Antonio Goncalves, a Java Champion, consultant, speaker, and book author on Microservices, Quarkus & Java EE"
  affiliation: "Antonio Goncalves"
  author: "Antonio Goncalves"
  id: "BuildingMicroservicesWithQuarkus_2021_05_11"
  type: "training"
  title: "Building Microservices with Quarkus"
  urldate: "2021-05-11"
- url: "https://agoncal.teachable.com/p/course-starting-with-quarkus"
  date: "2021-04-06"
  note: "Beginner's course to understand and start using Quarkus."
  affiliation: "agoncal"
  author: "Antonio Goncalves"
  id: "StartinGWithQuarkus_2021_04_06"
  type: "training"
  title: "Starting with Quarkus"
  urldate: "2021-04-06"
- url: "https://app.pluralsight.com/library/courses/quarkus-fundamentals/table-of-contents"
  date: "2021-01-15"
  note: "This course explains what Quarkus is so you can decide if it's suited for\
    \ your project."
  affiliation: "Pluralsight"
  author: "Antonio Goncalves"
  id: "QuarkusFundamentals_2021_01_15"
  type: "training"
  title: "Quarkus: Fundamentals"
  urldate: "2021-01-15"
- url: "https://www.katacoda.com/openshift/courses/middleware/middleware-quarkus"
  date: "2019-04-03"
  note: "Various Katacoda scenarios on Developing with Quarkus on OpenShift"
  affiliation: "Red Hat"
  author: "OpenShift"
  id: "DevelopingwithQuarkususingInteractiveBrowserBasedLabsKatacoda_2019_09_30"
  type: "training"
  title: "Developing with Quarkus using Interactive Browser-Based Labs | Katacoda"
  urldate: "2019-09-30"
- url: "https://quarkus.io/quarkus-workshops/super-heros"
  date: "2019-10-23"
  note: "A workshop where you build several microservices interoperating through HTTP\
    \ and Kafka."
  affiliation: "Red Hat"
  author: "Emmanuel Bernard, Clement Escoffier, Antonio Goncalves"
  id: "QuarkusWorkshopSuperHeroes_2019_10_23"
  type: "training"
  title: "Step-by-step Workshop on how to Develop a Microservice Architecture with\
    \ Quarkus"
  urldate: "2019-11-18"