---
name: Daily Build and deploy
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "develop"
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.1
      - name: Set up Bundler
        run: gem install bundler -v 2.0.2
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - name: Install dependencies
        run: bundle install
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - name: Build
        run: bundle exec jekyll build
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.PUSH_GITHUB_SECRET }}
          ACCESS_TOKEN: ${{ secrets.PUSH_GITHUB_SECRET }}
          BRANCH: gh-pages
          FOLDER: _site
          CLEAN: true
